/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package workshoptest;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Abhishek
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        // HidenLable.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextPhy = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextChem = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Maths = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextRollNO = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPassword = new javax.swing.JPasswordField();
        jButtonInsert = new javax.swing.JButton();
        jButtonSearch = new javax.swing.JButton();
        jButtonDelet = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        butUpdate = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HelloS");
        setBackground(new java.awt.Color(255, 204, 204));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNameActionPerformed(evt);
            }
        });
        jPanel1.add(jTextName, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 225, 180, 30));

        jLabel1.setBackground(new java.awt.Color(153, 255, 153));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Name ");
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 225, 105, 30));

        jTextPhy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPhyActionPerformed(evt);
            }
        });
        jPanel1.add(jTextPhy, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 315, 180, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Password");
        jLabel4.setOpaque(true);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 105, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Chem");
        jLabel5.setOpaque(true);
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 105, 30));

        jTextChem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextChemActionPerformed(evt);
            }
        });
        jPanel1.add(jTextChem, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, 180, 30));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Math");
        jLabel6.setOpaque(true);
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 405, 105, 30));

        Maths.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MathsActionPerformed(evt);
            }
        });
        jPanel1.add(Maths, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 405, 180, 30));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 255, 102));
        jLabel7.setText("Roll");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 180, 105, 45));

        jTextRollNO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextRollNOActionPerformed(evt);
            }
        });
        jPanel1.add(jTextRollNO, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 180, 30));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Physics");
        jLabel8.setOpaque(true);
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 315, 105, 30));

        jPassword.setToolTipText("");
        jPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 195, 30));

        jButtonInsert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/workshoptest/imgs/insert.jpg"))); // NOI18N
        jButtonInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(615, 465, 195, 60));

        jButtonSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/workshoptest/imgs/search.jpg"))); // NOI18N
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 465, 270, 60));

        jButtonDelet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/workshoptest/imgs/delet.jpg"))); // NOI18N
        jButtonDelet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeletActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonDelet, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 315, 225, 120));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/workshoptest/imgs/fb.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 15, 885, 90));

        butUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/workshoptest/imgs/update.jpg"))); // NOI18N
        butUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(butUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 465, 255, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 930, 540));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/workshoptest/imgs/nature.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 1, 990, 540));

        setSize(new java.awt.Dimension(1011, 597));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNameActionPerformed

    private void jTextPhyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPhyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPhyActionPerformed

    private void jTextChemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextChemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextChemActionPerformed

    private void MathsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MathsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MathsActionPerformed

    private void jTextRollNOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextRollNOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextRollNOActionPerformed

    private void jPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordActionPerformed

    private void jButtonInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertActionPerformed
        try {
            // TODO add your handling code here:
            
            Class.forName("com.mysql.jdbc.Driver");
     Connection con =DriverManager.getConnection("jdbc:Mysql://localhost:3306/workshoptest","root","root");
        //    System.out.println("Driver load Succesfully");
            PreparedStatement ps=null;
            
            String sql="insert into student(roll,name,password,phy,chem,math) values(?,?,?,?,?,?)";
         ps=con.prepareStatement(sql);
    
     ps.setInt(1,Integer.parseInt(jTextRollNO.getText()));
     ps.setString(2, jTextName.getText());
     ps.setString(3,(new String(jPassword.getPassword())));
     ps.setInt(4,Integer.parseInt(jTextPhy.getText()));
     ps.setInt(5,Integer.parseInt(jTextChem.getText()));    
     ps.setInt(6,Integer.parseInt(Maths.getText()));
      
     
       if(ps.executeUpdate()>0){
           JOptionPane.showMessageDialog(NewJFrame.this,"Data Inserted");
       }else
             JOptionPane.showMessageDialog(NewJFrame.this,"Data Not Inserted");
        
        
        } catch (Exception ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
    }//GEN-LAST:event_jButtonInsertActionPerformed

    private void jButtonDeletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeletActionPerformed
        // TODO add your handling code here:
        new NewDelet().setVisible(true);
      NewJFrame.this.dispose();
        
        
    }//GEN-LAST:event_jButtonDeletActionPerformed

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
 try{ Class.forName("com.mysql.jdbc.Driver");
     Connection con =DriverManager.getConnection("jdbc:Mysql://localhost:3306/workshoptest","root","root");
        //    System.out.println("Driver load Succesfully");
            PreparedStatement ps=null;
            
         int rnol=Integer.parseInt(JOptionPane.showInputDialog(this,"Enter Roll Number : "));
    String  sql="select * from student where roll=?";  
ps=con.prepareStatement(sql); 
//ps.setInt(1, Integer.parseInt(jTextRollNO.getText()));
ps.setInt(1, rnol);
ResultSet rs= ps.executeQuery();
if(rs.next()){
//    String data=" "+rs.getInt(1)+"   "+rs.getString(2)+"   "+rs.getString(3)+"  "
//            + " "+rs.getInt(4)+"   "+rs.getInt(5)+"   "+rs.getInt(6)+"   ";
       
    String data=" "+rs.getString(1)+"   "+rs.getString(2)+"   "+rs.getString(3)+"  "
            + " "+rs.getString(4)+"   "+rs.getString(5)+"   "+rs.getString(6)+"   ";
    jTextName.setText(rs.getString(3));
    jTextPhy.setText(rs.getString(5));
    jTextChem.setText(rs.getString(6));
    Maths.setText(rs.getString(7));
    jPassword.setText(rs.getString(4));
    jTextRollNO.setText(rs.getString(2));
   

// JOptionPane.showMessageDialog(NewJFrame.this,data);
      JOptionPane.showMessageDialog(NewJFrame.this,"Data Found");    
       }else
             JOptionPane.showMessageDialog(NewJFrame.this,"Data Not Found");
       } catch (Exception ex) {
            Logger.getLogger(NewDelet.class.getName()).log(Level.SEVERE, null, ex);
        }        
    }//GEN-LAST:event_jButtonSearchActionPerformed

    private void butUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butUpdateActionPerformed
        // TODO add your handling code here:
      try{ Class.forName("com.mysql.jdbc.Driver");
     Connection con =DriverManager.getConnection("jdbc:Mysql://localhost:3306/workshoptest","root","root");
        //    System.out.println("Driver load Succesfully");
            PreparedStatement ps=null;
         //int rnol=Integer.parseInt(JOptionPane.showInputDialog(this,"Enter Roll Number : "));
        //String sql="insert into student(roll,name,password,phy,chem,math) values(?,?,?,?,?,?)";
     String sql="update student set name=?,password=?,phy=?,chem=?,math=? where roll=?  ";
        ps=con.prepareStatement(sql);
     
         
         ps.setInt(6,Integer.parseInt(jTextRollNO.getText()));
     ps.setString(1, jTextName.getText());
     ps.setString(2,(new String(jPassword.getPassword())));
     ps.setInt(3,Integer.parseInt(jTextPhy.getText()));
      ps.setInt(4,Integer.parseInt(jTextChem.getText()));    
     ps.setInt(5,Integer.parseInt(Maths.getText()));
      
     
       if(ps.executeUpdate()>0){
           JOptionPane.showMessageDialog(NewJFrame.this,"Data Updated");
       }else
             JOptionPane.showMessageDialog(NewJFrame.this,"Not Found");
   
      } catch (Exception ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
         
         
    }//GEN-LAST:event_butUpdateActionPerformed
 int onClickCount=0;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Maths;
    private javax.swing.JButton butUpdate;
    private javax.swing.JButton jButtonDelet;
    private javax.swing.JButton jButtonInsert;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JTextField jTextChem;
    private javax.swing.JTextField jTextName;
    private javax.swing.JTextField jTextPhy;
    private javax.swing.JTextField jTextRollNO;
    // End of variables declaration//GEN-END:variables
}
